version: 2.1
orbs:
  # The orb is auto-injected into the pipeline.
  # Below, reference the jobs and commands as they appearpost-build.
  orb-tools: circleci/orb-tools@11.5
  slim-shield: slimdevops/slim-shield@dev:<<pipeline.git.revision>>


# Ensure test jobs always execute, while the publish job only runs on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
jobs:
  run-instrumented-container:
    # Specifies the type of executor for the job (docker,macos, or machine)
    docker: 
      - image: cimg/node:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Run Container
          command: |
            chmod +x ./src/scripts/run.sh
            ./src/scripts/run.sh
      - run:
          name: Stop Container
          command: |
            chmod +x ./src/scripts/cleanup.sh
            ./src/scripts/cleanup.sh
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - slim-shield/instrumentation:
          name: Instrumentation
          sourceImage: sreejithfocaloid/node-example
      - run-instrumented-container:
          name: Run Instrumented
          requires:
            - Instrumentation 
      - slim-shield/hardening:
          name: Hardening
          requires:
            - Run Instrumented
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: slimdevops/slim-shield
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - Instrumentation
            - Hardening
          context: orb-publishing
          filters: *release-filters
